export const COMPANY_DB: Record<string, string> = {
  "\u05e0\u05d8\u05e4\u05dc\u05d9\u05e7\u05e1": "netflix.com",
  "netflix": "netflix.com",
  "\u05e1\u05e4\u05d5\u05d8\u05d9\u05e4\u05d9\u05d9": "spotify.com",
  "spotify": "spotify.com",
  "\u05d0\u05e4\u05dc": "apple.com",
  "apple": "apple.com",
  "apple tv": "apple.com",
  "apple music": "apple.com",
  "icloud": "apple.com",
  "\u05d2\u05d5\u05d2\u05dc": "google.com",
  "google": "google.com",
  "google one": "one.google.com",
  "youtube": "youtube.com",
  "youtube premium": "youtube.com",
  "\u05d0\u05de\u05d6\u05d5\u05df": "amazon.com",
  "amazon": "amazon.com",
  "amazon prime": "amazon.com",
  "prime video": "primevideo.com",
  "\u05d3\u05d9\u05e1\u05e0\u05d9": "disneyplus.com",
  "disney": "disneyplus.com",
  "disney+": "disneyplus.com",
  "hbo": "hbomax.com",
  "hbo max": "hbomax.com",
  "max": "max.com",
  "\u05e1\u05dc\u05e7\u05d5\u05dd": "cellcom.co.il",
  "cellcom": "cellcom.co.il",
  "\u05e4\u05e8\u05d8\u05e0\u05e8": "partner.co.il",
  "partner": "partner.co.il",
  "\u05e4\u05dc\u05d0\u05e4\u05d5\u05df": "pelephone.co.il",
  "pelephone": "pelephone.co.il",
  "\u05d4\u05d5\u05d8": "hot.net.il",
  "hot": "hot.net.il",
  "yes": "yes.co.il",
  "\u05d9\u05e1": "yes.co.il",
  "\u05d1\u05d6\u05e7": "bezeq.co.il",
  "bezeq": "bezeq.co.il",
  "\u05e1\u05dc\u05e7\u05d5\u05dd tv": "cellcomtv.co.il",
  "wolt": "wolt.com",
  "\u05d5\u05d5\u05dc\u05d8": "wolt.com",
  "bolt": "bolt.eu",
  "\u05d1\u05d5\u05dc\u05d8": "bolt.eu",
  "gett": "gett.com",
  "\u05d2\u05d8": "gett.com",
  "yango": "yango.com",
  "\u05de\u05db\u05d1\u05d9": "maccabi4u.co.il",
  "maccabi": "maccabi4u.co.il",
  "\u05db\u05dc\u05dc\u05d9\u05ea": "clalit.co.il",
  "clalit": "clalit.co.il",
  "\u05dc\u05d0\u05d5\u05de\u05d9\u05ea": "leumit.co.il",
  "leumit": "leumit.co.il",
  "\u05de\u05d0\u05d5\u05d7\u05d3\u05ea": "meuhedet.co.il",
  "meuhedet": "meuhedet.co.il",
  "\u05d1\u05d9\u05d8\u05d5\u05d7 \u05dc\u05d0\u05d5\u05de\u05d9": "btl.gov.il",
  "\u05db\u05d0\u05df": "kan.org.il",
  "\u05d7\u05d9\u05e0\u05d5\u05db\u05d9\u05ea": "iba.org.il",
  "freetv": "freetv.co.il",
  "free tv": "freetv.co.il",
  "\u05e4\u05e8\u05d9\u05d8\u05d9\u05d5\u05d9": "freetv.co.il",
  "\u05e4\u05e8\u05d9 \u05d8\u05d9\u05d5\u05d9": "freetv.co.il",
  "\u05e4\u05e8\u05d9 \u05d8\u05d9 \u05d5\u05d9": "freetv.co.il",
  "\u05d5\u05d5\u05d9\u05e0\u05d3\u05e1": "winds.co.il",
  "012": "012.net.il",
  "013": "013netvision.net.il",
  "\u05d0\u05e7\u05e1\u05e4\u05e8\u05e1 vpn": "expressvpn.com",
  "expressvpn": "expressvpn.com",
  "nordvpn": "nordvpn.com",
  "surfshark": "surfshark.com",
  "wix": "wix.com",
  "\u05d5\u05d5\u05d9\u05e7\u05e1": "wix.com",
  "monday": "monday.com",
  "\u05de\u05d0\u05e0\u05d3\u05d9\u05d9": "monday.com",
  "fiverr": "fiverr.com",
  "\u05e4\u05d9\u05d9\u05d1\u05e8": "fiverr.com",
  "elementor": "elementor.com",
  "canva": "canva.com",
  "\u05e7\u05e0\u05d1\u05d4": "canva.com",
  "adobe": "adobe.com",
  "\u05d0\u05d3\u05d5\u05d1\u05d9": "adobe.com",
  "photoshop": "adobe.com",
  "illustrator": "adobe.com",
  "premiere": "adobe.com",
  "figma": "figma.com",
  "notion": "notion.so",
  "dropbox": "dropbox.com",
  "\u05d3\u05e8\u05d5\u05e4\u05d1\u05d5\u05e7\u05e1": "dropbox.com",
  "microsoft": "microsoft.com",
  "\u05de\u05d9\u05d9\u05e7\u05e8\u05d5\u05e1\u05d5\u05e4\u05d8": "microsoft.com",
  "office": "microsoft.com",
  "microsoft 365": "microsoft.com",
  "onedrive": "microsoft.com",
  "zoom": "zoom.us",
  "slack": "slack.com",
  "github": "github.com",
  "openai": "openai.com",
  "chatgpt": "openai.com",
  "claude": "anthropic.com",
  "anthropic": "anthropic.com",
  "midjourney": "midjourney.com",
  "grammarly": "grammarly.com",
  "duolingo": "duolingo.com",
  "headspace": "headspace.com",
  "calm": "calm.com",
  "strava": "strava.com",
  "peloton": "onepeloton.com",
  "hulu": "hulu.com",
  "peacock": "peacocktv.com",
  "paramount": "paramountplus.com",
  "paramount+": "paramountplus.com",
  "crunchyroll": "crunchyroll.com",
  "tidal": "tidal.com",
  "deezer": "deezer.com",
  "audible": "audible.com",
  "kindle": "amazon.com",
  "xbox": "xbox.com",
  "xbox game pass": "xbox.com",
  "playstation": "playstation.com",
  "ps plus": "playstation.com",
  "nintendo": "nintendo.com",
  "nintendo switch online": "nintendo.com",
  "steam": "steampowered.com",
  "ea play": "ea.com",
  "ea": "ea.com",
  "twitch": "twitch.tv",
  "linkedin": "linkedin.com",
  "linkedin premium": "linkedin.com",
  "twitter": "x.com",
  "x premium": "x.com",
  "reddit": "reddit.com",
  "medium": "medium.com",
  "substack": "substack.com",
  "patreon": "patreon.com",
  "tinder": "tinder.com",
  "bumble": "bumble.com",
  "doordash": "doordash.com",
  "uber eats": "ubereats.com",
  "uber": "uber.com",
  "instacart": "instacart.com",
  "walmart+": "walmart.com",
  "walmart": "walmart.com",
  "costco": "costco.com",
  "hellofresh": "hellofresh.com",
  "noom": "noom.com",
  "evernote": "evernote.com",
  "todoist": "todoist.com",
  "trello": "trello.com",
  "asana": "asana.com",
  "jira": "atlassian.com",
  "atlassian": "atlassian.com",
  "gitlab": "gitlab.com",
  "vercel": "vercel.com",
  "netlify": "netlify.com",
  "heroku": "heroku.com",
  "digitalocean": "digitalocean.com",
  "cloudflare": "cloudflare.com",
  "godaddy": "godaddy.com",
  "squarespace": "squarespace.com",
  "shopify": "shopify.com",
  "wordpress": "wordpress.com",
  "mailchimp": "mailchimp.com",
  "hubspot": "hubspot.com",
  "salesforce": "salesforce.com",
  "stripe": "stripe.com",
  "paypal": "paypal.com",
  "\u05e4\u05d9\u05d9\u05e4\u05d0\u05dc": "paypal.com",
  "revolut": "revolut.com",
  "wise": "wise.com",
  "1password": "1password.com",
  "lastpass": "lastpass.com",
  "protonvpn": "protonvpn.com",
  "proton": "proton.me",
  "nytimes": "nytimes.com",
  "new york times": "nytimes.com",
  "haaretz": "haaretz.co.il",
  "\u05d4\u05d0\u05e8\u05e5": "haaretz.co.il",
  "ynet": "ynet.co.il",
  "\u05db\u05dc\u05db\u05dc\u05d9\u05e1\u05d8": "calcalist.co.il",
  "calcalist": "calcalist.co.il",
  "\u05d2\u05dc\u05d5\u05d1\u05e1": "globes.co.il",
  "globes": "globes.co.il"
};
