export const COMPANY_DB: Record<string, string> = {
  // ── Streaming & Entertainment ──────────────────────────────
  "נטפליקס": "netflix.com",
  "netflix": "netflix.com",
  "ספוטיפיי": "spotify.com",
  "spotify": "spotify.com",
  "אפל": "apple.com",
  "apple": "apple.com",
  "apple tv": "apple.com",
  "apple tv+": "apple.com",
  "apple music": "apple.com",
  "icloud": "apple.com",
  "icloud+": "apple.com",
  "גוגל": "google.com",
  "google": "google.com",
  "google one": "one.google.com",
  "youtube": "youtube.com",
  "youtube premium": "youtube.com",
  "אמזון": "amazon.com",
  "amazon": "amazon.com",
  "amazon prime": "amazon.com",
  "prime video": "primevideo.com",
  "דיסני": "disneyplus.com",
  "disney": "disneyplus.com",
  "disney+": "disneyplus.com",
  "hbo": "hbomax.com",
  "hbo max": "hbomax.com",
  "max": "max.com",
  "hulu": "hulu.com",
  "peacock": "peacocktv.com",
  "paramount": "paramountplus.com",
  "paramount+": "paramountplus.com",
  "crunchyroll": "crunchyroll.com",
  "funimation": "funimation.com",
  "mubi": "mubi.com",
  "dazn": "dazn.com",
  "discovery+": "discoveryplus.com",
  "discovery": "discoveryplus.com",
  "espn+": "espnplus.com",
  "espn": "espnplus.com",
  "curiositystream": "curiositystream.com",
  "nebula": "nebula.tv",
  "dropout": "dropout.tv",
  "britbox": "britbox.com",
  "acorn tv": "acorn.tv",
  "shudder": "shudder.com",
  "tubi": "tubitv.com",
  "pluto tv": "pluto.tv",
  "plex": "plex.tv",
  "emby": "emby.media",
  "jellyfin": "jellyfin.org",

  // ── Israeli Telecom & TV ───────────────────────────────────
  "סלקום": "cellcom.co.il",
  "cellcom": "cellcom.co.il",
  "פרטנר": "partner.co.il",
  "partner": "partner.co.il",
  "פלאפון": "pelephone.co.il",
  "pelephone": "pelephone.co.il",
  "הוט": "hot.net.il",
  "hot": "hot.net.il",
  "yes": "yes.co.il",
  "יס": "yes.co.il",
  "בזק": "bezeq.co.il",
  "bezeq": "bezeq.co.il",
  "סלקום tv": "cellcomtv.co.il",
  "hot mobile": "hot.net.il",
  "רמי לוי תקשורת": "ralev.co.il",
  "019 mobile": "019mobile.co.il",
  "012": "012.net.il",
  "013": "013netvision.net.il",
  "וינדס": "winds.co.il",

  // ── Israeli Media & News ────────────────────────────────────
  "כאן": "kan.org.il",
  "חינוכית": "iba.org.il",
  "מאקו": "mako.co.il",
  "mako": "mako.co.il",
  "רשת 13": "reshet.tv",
  "reshet": "reshet.tv",
  "ספורט 5": "sport5.co.il",
  "sport5": "sport5.co.il",
  "one": "one.co.il",
  "הארץ": "haaretz.co.il",
  "haaretz": "haaretz.co.il",
  "ידיעות": "ynet.co.il",
  "ynet": "ynet.co.il",
  "כלכליסט": "calcalist.co.il",
  "calcalist": "calcalist.co.il",
  "גלובס": "globes.co.il",
  "globes": "globes.co.il",
  "ישראל היום": "israelhayom.co.il",
  "israel hayom": "israelhayom.co.il",
  "מעריב": "maariv.co.il",
  "maariv": "maariv.co.il",
  "freetv": "freetv.co.il",
  "free tv": "freetv.co.il",
  "פריטיוי": "freetv.co.il",

  // ── Israeli Health ──────────────────────────────────────────
  "מכבי": "maccabi4u.co.il",
  "maccabi": "maccabi4u.co.il",
  "כללית": "clalit.co.il",
  "clalit": "clalit.co.il",
  "לאומית": "leumit.co.il",
  "leumit": "leumit.co.il",
  "מאוחדת": "meuhedet.co.il",
  "meuhedet": "meuhedet.co.il",
  "ביטוח לאומי": "btl.gov.il",

  // ── Israeli Tech & Startups ─────────────────────────────────
  "וויקס": "wix.com",
  "wix": "wix.com",
  "מאנדיי": "monday.com",
  "monday": "monday.com",
  "פייבר": "fiverr.com",
  "fiverr": "fiverr.com",
  "elementor": "elementor.com",
  "taboola": "taboola.com",
  "ironsource": "is.com",
  "waze": "waze.com",
  "riskified": "riskified.com",
  "walkme": "walkme.com",
  "nice": "nice.com",
  "checkpoint": "checkpoint.com",
  "check point": "checkpoint.com",
  "amdocs": "amdocs.com",
  "radware": "radware.com",

  // ── Israeli Delivery & Transport ───────────────────────────
  "וולט": "wolt.com",
  "wolt": "wolt.com",
  "בולט": "bolt.eu",
  "bolt": "bolt.eu",
  "גט": "gett.com",
  "gett": "gett.com",
  "יאנגו": "yango.com",
  "yango": "yango.com",
  "ten bis": "10bis.co.il",
  "תן ביס": "10bis.co.il",
  "10bis": "10bis.co.il",

  // ── Music ───────────────────────────────────────────────────
  "tidal": "tidal.com",
  "deezer": "deezer.com",
  "audible": "audible.com",
  "kindle": "amazon.com",
  "kindle unlimited": "amazon.com",
  "pandora": "pandora.com",
  "soundcloud": "soundcloud.com",
  "bandcamp": "bandcamp.com",
  "qobuz": "qobuz.com",

  // ── Gaming ──────────────────────────────────────────────────
  "xbox": "xbox.com",
  "xbox game pass": "xbox.com",
  "game pass": "xbox.com",
  "playstation": "playstation.com",
  "ps plus": "playstation.com",
  "ps now": "playstation.com",
  "nintendo": "nintendo.com",
  "nintendo switch online": "nintendo.com",
  "steam": "steampowered.com",
  "ea play": "ea.com",
  "ea": "ea.com",
  "epic games": "epicgames.com",
  "humble bundle": "humblebundle.com",
  "gog": "gog.com",
  "twitch": "twitch.tv",
  "twitch prime": "twitch.tv",
  "ubisoft": "ubisoft.com",
  "ubisoft+": "ubisoft.com",
  "battlenet": "blizzard.com",
  "battle.net": "blizzard.com",
  "blizzard": "blizzard.com",
  "roblox": "roblox.com",

  // ── AI & Developer Tools ────────────────────────────────────
  "openai": "openai.com",
  "chatgpt": "openai.com",
  "chatgpt plus": "openai.com",
  "gpt-4": "openai.com",
  "claude": "anthropic.com",
  "anthropic": "anthropic.com",
  "xai": "x.ai",
  "x.ai": "x.ai",
  "grok": "x.ai",
  "perplexity": "perplexity.ai",
  "perplexity ai": "perplexity.ai",
  "midjourney": "midjourney.com",
  "runway": "runwayml.com",
  "runwayml": "runwayml.com",
  "runway ml": "runwayml.com",
  "pika": "pika.art",
  "pika labs": "pika.art",
  "suno": "suno.com",
  "udio": "udio.com",
  "elevenlabs": "elevenlabs.io",
  "eleven labs": "elevenlabs.io",
  "cursor": "cursor.com",
  "github copilot": "github.com",
  "copilot": "github.com",
  "jasper": "jasper.ai",
  "jasper ai": "jasper.ai",
  "copy.ai": "copy.ai",
  "writesonic": "writesonic.com",
  "synthesia": "synthesia.io",
  "heygen": "heygen.com",
  "d-id": "d-id.com",
  "did": "d-id.com",
  "luma": "lumalabs.ai",
  "luma ai": "lumalabs.ai",
  "stability ai": "stability.ai",
  "stable diffusion": "stability.ai",
  "ideogram": "ideogram.ai",
  "leonardo": "leonardo.ai",
  "leonardo ai": "leonardo.ai",
  "cohere": "cohere.com",
  "hugging face": "huggingface.co",
  "huggingface": "huggingface.co",
  "replicate": "replicate.com",
  "grammarly": "grammarly.com",
  "otter": "otter.ai",
  "otter.ai": "otter.ai",
  "fireflies": "fireflies.ai",
  "krisp": "krisp.ai",
  "descript": "descript.com",
  "riverside": "riverside.fm",
  "riverside.fm": "riverside.fm",
  "higgsfield": "higgsfield.ai",

  // ── Productivity & Project Management ──────────────────────
  "notion": "notion.so",
  "dropbox": "dropbox.com",
  "דרופבוקס": "dropbox.com",
  "evernote": "evernote.com",
  "todoist": "todoist.com",
  "trello": "trello.com",
  "asana": "asana.com",
  "jira": "atlassian.com",
  "atlassian": "atlassian.com",
  "confluence": "atlassian.com",
  "clickup": "clickup.com",
  "airtable": "airtable.com",
  "linear": "linear.app",
  "basecamp": "basecamp.com",
  "miro": "miro.com",
  "loom": "loom.com",
  "calendly": "calendly.com",
  "typeform": "typeform.com",
  "surveymonkey": "surveymonkey.com",
  "obsidian": "obsidian.md",
  "readwise": "readwise.io",
  "speechify": "speechify.com",

  // ── Design & Creative ───────────────────────────────────────
  "canva": "canva.com",
  "קנבה": "canva.com",
  "adobe": "adobe.com",
  "אדובי": "adobe.com",
  "photoshop": "adobe.com",
  "illustrator": "adobe.com",
  "premiere": "adobe.com",
  "after effects": "adobe.com",
  "lightroom": "adobe.com",
  "acrobat": "adobe.com",
  "figma": "figma.com",
  "framer": "framer.com",
  "webflow": "webflow.com",
  "sketch": "sketch.com",
  "procreate": "procreate.art",
  "affinity": "affinity.serif.com",
  "davinci resolve": "blackmagicdesign.com",
  "capcut": "capcut.com",
  "cap cut": "capcut.com",

  // ── Social Media ────────────────────────────────────────────
  "linkedin": "linkedin.com",
  "linkedin premium": "linkedin.com",
  "twitter": "x.com",
  "x premium": "x.com",
  "x corp": "x.com",
  "reddit": "reddit.com",
  "medium": "medium.com",
  "substack": "substack.com",
  "patreon": "patreon.com",
  "tiktok": "tiktok.com",
  "instagram": "instagram.com",
  "facebook": "facebook.com",
  "meta": "meta.com",
  "discord": "discord.com",
  "telegram": "telegram.org",
  "signal": "signal.org",
  "viber": "viber.com",
  "whatsapp": "whatsapp.com",
  "snapchat": "snapchat.com",
  "pinterest": "pinterest.com",
  "tumblr": "tumblr.com",
  "mastodon": "mastodon.social",
  "bluesky": "bsky.app",
  "threads": "threads.net",

  // ── Communication & Meetings ────────────────────────────────
  "מיקרוסופט": "microsoft.com",
  "microsoft": "microsoft.com",
  "office": "microsoft.com",
  "microsoft 365": "microsoft.com",
  "onedrive": "microsoft.com",
  "teams": "microsoft.com",
  "outlook": "microsoft.com",
  "skype": "skype.com",
  "zoom": "zoom.us",
  "slack": "slack.com",
  "webex": "webex.com",
  "ringcentral": "ringcentral.com",
  "vonage": "vonage.com",
  "twilio": "twilio.com",
  "lark": "larksuite.com",

  // ── Cloud & Developer ───────────────────────────────────────
  "github": "github.com",
  "gitlab": "gitlab.com",
  "vercel": "vercel.com",
  "netlify": "netlify.com",
  "heroku": "heroku.com",
  "digitalocean": "digitalocean.com",
  "cloudflare": "cloudflare.com",
  "aws": "aws.amazon.com",
  "amazon web services": "aws.amazon.com",
  "google cloud": "cloud.google.com",
  "azure": "azure.microsoft.com",
  "microsoft azure": "azure.microsoft.com",
  "datadog": "datadoghq.com",
  "sentry": "sentry.io",
  "new relic": "newrelic.com",
  "supabase": "supabase.com",
  "mongodb": "mongodb.com",
  "mongodb atlas": "mongodb.com",
  "railway": "railway.app",
  "render": "render.com",
  "fly.io": "fly.io",
  "planetscale": "planetscale.com",
  "neon": "neon.tech",

  // ── Websites & E-commerce ───────────────────────────────────
  "godaddy": "godaddy.com",
  "squarespace": "squarespace.com",
  "shopify": "shopify.com",
  "wordpress": "wordpress.com",
  "woocommerce": "woocommerce.com",
  "bigcommerce": "bigcommerce.com",
  "etsy": "etsy.com",
  "ebay": "ebay.com",
  "aliexpress": "aliexpress.com",
  "amazon.co.il": "amazon.co.il",

  // ── Marketing & CRM ─────────────────────────────────────────
  "mailchimp": "mailchimp.com",
  "hubspot": "hubspot.com",
  "salesforce": "salesforce.com",
  "activecampaign": "activecampaign.com",
  "klaviyo": "klaviyo.com",
  "brevo": "brevo.com",
  "sendinblue": "brevo.com",
  "convertkit": "convertkit.com",
  "getresponse": "getresponse.com",
  "sendgrid": "sendgrid.com",
  "intercom": "intercom.com",
  "zendesk": "zendesk.com",
  "freshdesk": "freshdesk.com",
  "hotjar": "hotjar.com",
  "mixpanel": "mixpanel.com",
  "amplitude": "amplitude.com",
  "segment": "segment.com",
  "google analytics": "google.com",

  // ── Finance & Payments ──────────────────────────────────────
  "stripe": "stripe.com",
  "פייפאל": "paypal.com",
  "paypal": "paypal.com",
  "revolut": "revolut.com",
  "wise": "wise.com",
  "robinhood": "robinhood.com",
  "coinbase": "coinbase.com",
  "binance": "binance.com",
  "trading212": "trading212.com",
  "etoro": "etoro.com",
  "interactive brokers": "ibkr.com",
  "quickbooks": "quickbooks.com",
  "xero": "xero.com",
  "freshbooks": "freshbooks.com",

  // ── Security & Privacy ──────────────────────────────────────
  "expressvpn": "expressvpn.com",
  "אקספרס vpn": "expressvpn.com",
  "nordvpn": "nordvpn.com",
  "surfshark": "surfshark.com",
  "protonvpn": "protonvpn.com",
  "proton": "proton.me",
  "proton mail": "proton.me",
  "protonmail": "proton.me",
  "1password": "1password.com",
  "lastpass": "lastpass.com",
  "bitwarden": "bitwarden.com",
  "dashlane": "dashlane.com",
  "keeper": "keepersecurity.com",
  "nordpass": "nordpass.com",
  "avast": "avast.com",
  "malwarebytes": "malwarebytes.com",
  "norton": "norton.com",
  "bitdefender": "bitdefender.com",
  "kaspersky": "kaspersky.com",

  // ── Cloud Storage ───────────────────────────────────────────
  "box": "box.com",
  "mega": "mega.io",
  "pcloud": "pcloud.com",
  "backblaze": "backblaze.com",
  "idrive": "idrive.com",
  "wasabi": "wasabi.com",

  // ── Food & Delivery ─────────────────────────────────────────
  "doordash": "doordash.com",
  "uber eats": "ubereats.com",
  "uber": "uber.com",
  "instacart": "instacart.com",
  "hellofresh": "hellofresh.com",
  "factor": "factor75.com",

  // ── Health & Fitness ────────────────────────────────────────
  "headspace": "headspace.com",
  "calm": "calm.com",
  "strava": "strava.com",
  "peloton": "onepeloton.com",
  "noom": "noom.com",
  "myfitnesspal": "myfitnesspal.com",
  "fitbit": "fitbit.com",
  "whoop": "whoop.com",
  "eight sleep": "eightsleep.com",

  // ── Education ───────────────────────────────────────────────
  "duolingo": "duolingo.com",
  "coursera": "coursera.org",
  "udemy": "udemy.com",
  "skillshare": "skillshare.com",
  "masterclass": "masterclass.com",
  "linkedin learning": "linkedin.com",
  "pluralsight": "pluralsight.com",
  "datacamp": "datacamp.com",
  "codecademy": "codecademy.com",
  "brilliant": "brilliant.org",
  "khan academy": "khanacademy.org",
  "chegg": "chegg.com",
  "blinkist": "blinkist.com",

  // ── Dating ──────────────────────────────────────────────────
  "tinder": "tinder.com",
  "bumble": "bumble.com",
  "hinge": "hinge.co",
  "match": "match.com",
  "eharmony": "eharmony.com",
  "jdate": "jdate.com",
  "zoosk": "zoosk.com",

  // ── News & Reading ──────────────────────────────────────────
  "nytimes": "nytimes.com",
  "new york times": "nytimes.com",
  "washington post": "washingtonpost.com",
  "wall street journal": "wsj.com",
  "wsj": "wsj.com",
  "the guardian": "theguardian.com",
  "economist": "economist.com",
  "financial times": "ft.com",
  "ft": "ft.com",
  "wired": "wired.com",
  "pocket": "getpocket.com",
  "feedly": "feedly.com",

  // ── Podcast & Audio ─────────────────────────────────────────
  "buzzsprout": "buzzsprout.com",
  "transistor": "transistor.fm",
  "captivate": "captivate.fm",
  "anchor": "spotify.com",

  // ── Retail & Shopping ───────────────────────────────────────
  "walmart+": "walmart.com",
  "walmart": "walmart.com",
  "costco": "costco.com",
  "sam's club": "samsclub.com",
  "nike": "nike.com",
  "adidas": "adidas.com",
  "h&m": "hm.com",
  "zara": "zara.com",
  "asos": "asos.com",
  "zalando": "zalando.com",
  "farfetch": "farfetch.com",

  // ── Misc / Developer ────────────────────────────────────────
  "jetbrains": "jetbrains.com",
  "intellij": "jetbrains.com",
  "pycharm": "jetbrains.com",
  "webstorm": "jetbrains.com",
  "zapier": "zapier.com",
  "make": "make.com",
  "n8n": "n8n.io",
  "retool": "retool.com",
  "bubble": "bubble.io",
  "softr": "softr.io",
  "glide": "glideapps.com",
};
